Repository QuantumSavory/QuantumClifford.jl, pull requests merged in 2025-06, with the labels that each got.

#498 improvements to `GeneralizedStabillizer` API: `sm⊗S"X"`, `pcT⊗P"X"`, `pcT*sm`, `pcT⊗pcT`
  CHANGELOG.md
  src/classical_register.jl
  src/nonclifford.jl
  test/test_classicalreg.jl
  test/test_nonclifford.jl
  test/test_nonclifford_quantumoptics.jl
Labels: nonclifford

#439 compute the minimum distance of QLDPC using Mixed Integer Programming
  CHANGELOG.md
  Project.toml
  docs/Project.toml
  docs/make.jl
  docs/src/ECC_API.md
  docs/src/references.bib
  docs/src/references.md
  ext/QuantumCliffordHeckeExt/QuantumCliffordHeckeExt.jl
  ext/QuantumCliffordHeckeExt/lifted.jl
  ext/QuantumCliffordHeckeExt/lifted_product.jl
  ext/QuantumCliffordJuMPExt/QuantumCliffordJuMPExt.jl
  ext/QuantumCliffordJuMPExt/min_distance_mixed_integer_programming.jl
  lib/QECCore/src/QECCore.jl
  lib/QECCore/src/interface.jl
  src/QuantumClifford.jl
  src/ecc/ECC.jl
  src/ecc/codes/color_codes.jl
  src/nonclifford.jl
  test/Project.toml
  test/test_ecc_2bga.jl
  test/test_ecc_bivaraite_bicycle_as_twobga.jl
  test/test_ecc_color_codes.jl
  test/test_ecc_coprime_bivaraite_bicycle.jl
  test/test_ecc_generalized_bicycle_codes.jl
  test/test_ecc_minimum_distance.jl
  test/test_ecc_multivariate_bicycle.jl
  test/test_jet.jl
Labels: bug bounty, bounty:400

#441 more tests of bivariate bicycle codes
  test/test_ecc_bivaraite_bicycle_as_twobga.jl
Labels: ECC, Skip-Changelog

#512 clean up LinAlg import
  src/nonclifford.jl
Labels: Skip-Changelog

#517 fix jet tests and use buildkite better
  .buildkite/pipeline.yml
  .github/workflows/ci-julia-nightly.yml
  test/runtests.jl
  test/test_jet.jl
Labels: Skip-Changelog

#529 strided SubArray does not work with SIMD.jl
  src/mul_leftright.jl
Labels: Skip-Changelog

#530 remove unreliable `upper_bound` from mip distance solver
  ext/QuantumCliffordJuMPExt/min_distance_mixed_integer_programming.jl
  src/ecc/ECC.jl
Labels: Skip-Changelog
