Repository QuantumSavory/QuantumClifford.jl, pull requests merged in 2025-07, with the labels that each got.

#535 add a commutativity check to the LPCode constructor
  ext/QuantumCliffordHeckeExt/lifted_product.jl
  ext/QuantumCliffordOscarExt/group_presentation.jl
  lib/QECCore/src/codes/css.jl
Labels: Skip-Changelog

#543 guard against iscss being nothing (detected by JET)
  src/ecc/codes/concat.jl
Labels: Skip-Changelog

#437 improve parameter handling on BCH code, add docs and more tests
  src/ecc/codes/classical/bch.jl
  test/test_ecc_bch.jl
  test/test_ecc_throws.jl
Labels: documentation, ECC, Skip-Changelog

#546 add changelogs of PRs
  CHANGELOG.md
Labels: Skip-Changelog

#533 add: `GraphState` type
  src/QuantumClifford.jl
  src/graphs/graphs.jl
  src/symbolic_cliffords.jl
  test/test_graphs.jl
Labels: Skip-Changelog

#466 Delfosse-Reichardt codes from classical self-orthogonal Reed-Muller seeds
  CHANGELOG.md
  lib/QECCore/CHANGELOG.md
  lib/QECCore/src/QECCore.jl
  lib/QECCore/src/codes/quantum/color_codes.jl
  lib/QECCore/src/codes/quantum/delfosse_reichardt_code.jl
  lib/QECCore/src/codes/quantum/surface.jl
  lib/QECCore/src/codes/quantum/toric.jl
  lib/QECCore/test/codes/delfosse_reichardt_code.jl
  lib/QECCore/test/test_codes.jl
  src/ecc/ECC.jl
  src/ecc/codes/classical/bch.jl
  test/test_ecc_base.jl
  test/test_ecc_bch.jl
Labels: ECC

#468 `[[8p, 4p − 2, 3]]` Delfosse-Reichardt Generalized `[[8,2,3]]` code
  CHANGELOG.md
  ext/QuantumCliffordHeckeExt/lifted_product.jl
  lib/QECCore/CHANGELOG.md
  lib/QECCore/src/QECCore.jl
  lib/QECCore/src/codes/quantum/delfosse_reichardt_823_code.jl
  lib/QECCore/test/codes/delfosse_reichardt_823_code.jl
  lib/QECCore/test/codes/delfosse_reichardt_code.jl
  lib/QECCore/test/test_codes.jl
  src/ecc/ECC.jl
  test/test_ecc_base.jl
Labels: ECC

#557 Added good_state validation for VerifyOp and included test for it
  src/misc_ops.jl
  test/test_noisycircuits.jl
Labels: Skip-Changelog

#476 `[[n² + m², (n - rank([C ∣ M]))² + (m − rank([C ∣ M]ᵀ))², d]]` quantum Tillich-Zémor code
  .typos.toml
  CHANGELOG.md
  docs/src/references.bib
  docs/src/references.md
  lib/QECCore/CHANGELOG.md
  lib/QECCore/Project.toml
  lib/QECCore/ext/QECCoreNemoExt.jl
  lib/QECCore/src/QECCore.jl
  lib/QECCore/src/codes/quantum/tillichzemor.jl
  lib/QECCore/test/codes/tillichzemor.jl
  lib/QECCore/test/test_codes.jl
  src/ecc/ECC.jl
  test/test_ecc_base.jl
Labels: ECC

#563 derive the `N`, `K` parameters for `DDimensionalToricCode`
  ext/QuantumCliffordHeckeExt/lacross.jl
  ext/QuantumCliffordOscarExt/d_dimensional_codes.jl
  lib/QECCore/src/codes/quantum/tillichzemor.jl
  lib/QECCore/test/codes/tillichzemor.jl
  test/test_ecc_d_dimensional_codes.jl
Labels: documentation, Skip-Changelog

#550 default to computing the ``min(d_X, d_X)`` instead of ``d_X``
  docs/src/references.bib
  ext/QuantumCliffordJuMPExt/min_distance_mixed_integer_programming.jl
  src/ecc/ECC.jl
  test/test_ecc_d_dimensional_codes.jl
  test/test_ecc_minimum_distance.jl
Labels: Skip-Changelog
